[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.gd"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --ignore-platform-req=ext-gd"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/"