[variables]
NIXPACKS_PHP_VERSION = "8.2"

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --no-scripts --ignore-platform-reqs --no-interaction"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/"