<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Animaux extends \App\Entity\Animaux implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'date_naissance' => [parent::class, 'date_naissance', null, 16],
        "\0".parent::class."\0".'espece' => [parent::class, 'espece', null, 16],
        "\0".parent::class."\0".'examen' => [parent::class, 'examen', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'poids' => [parent::class, 'poids', null, 16],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null, 16],
        'date_naissance' => [parent::class, 'date_naissance', null, 16],
        'espece' => [parent::class, 'espece', null, 16],
        'examen' => [parent::class, 'examen', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'poids' => [parent::class, 'poids', null, 16],
        'sexe' => [parent::class, 'sexe', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
