<?php

namespace Container5jCnL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FvJHjidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FvJHjid' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AnimauxController::delete' => ['privates', '.service_locator.aVVMrX4', 'get_ServiceLocator_AVVMrX4Service', true],
            'App\\Controller\\AnimauxController::edit' => ['privates', '.service_locator.aVVMrX4', 'get_ServiceLocator_AVVMrX4Service', true],
            'App\\Controller\\AnimauxController::index' => ['privates', '.service_locator.H2SgVt9', 'get_ServiceLocator_H2SgVt9Service', true],
            'App\\Controller\\AnimauxController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnimauxController::show' => ['privates', '.service_locator.93oAlYQ', 'get_ServiceLocator_93oAlYQService', true],
            'App\\Controller\\ExamensController::delete' => ['privates', '.service_locator.ty0Rl4X', 'get_ServiceLocator_Ty0Rl4XService', true],
            'App\\Controller\\ExamensController::edit' => ['privates', '.service_locator.ty0Rl4X', 'get_ServiceLocator_Ty0Rl4XService', true],
            'App\\Controller\\ExamensController::index' => ['privates', '.service_locator.DwIO0fk', 'get_ServiceLocator_DwIO0fkService', true],
            'App\\Controller\\ExamensController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ExamensController::show' => ['privates', '.service_locator.h__ZqfX', 'get_ServiceLocator_HZqfXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AnimauxController:delete' => ['privates', '.service_locator.aVVMrX4', 'get_ServiceLocator_AVVMrX4Service', true],
            'App\\Controller\\AnimauxController:edit' => ['privates', '.service_locator.aVVMrX4', 'get_ServiceLocator_AVVMrX4Service', true],
            'App\\Controller\\AnimauxController:index' => ['privates', '.service_locator.H2SgVt9', 'get_ServiceLocator_H2SgVt9Service', true],
            'App\\Controller\\AnimauxController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AnimauxController:show' => ['privates', '.service_locator.93oAlYQ', 'get_ServiceLocator_93oAlYQService', true],
            'App\\Controller\\ExamensController:delete' => ['privates', '.service_locator.ty0Rl4X', 'get_ServiceLocator_Ty0Rl4XService', true],
            'App\\Controller\\ExamensController:edit' => ['privates', '.service_locator.ty0Rl4X', 'get_ServiceLocator_Ty0Rl4XService', true],
            'App\\Controller\\ExamensController:index' => ['privates', '.service_locator.DwIO0fk', 'get_ServiceLocator_DwIO0fkService', true],
            'App\\Controller\\ExamensController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ExamensController:show' => ['privates', '.service_locator.h__ZqfX', 'get_ServiceLocator_HZqfXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AnimauxController::delete' => '?',
            'App\\Controller\\AnimauxController::edit' => '?',
            'App\\Controller\\AnimauxController::index' => '?',
            'App\\Controller\\AnimauxController::new' => '?',
            'App\\Controller\\AnimauxController::show' => '?',
            'App\\Controller\\ExamensController::delete' => '?',
            'App\\Controller\\ExamensController::edit' => '?',
            'App\\Controller\\ExamensController::index' => '?',
            'App\\Controller\\ExamensController::new' => '?',
            'App\\Controller\\ExamensController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AnimauxController:delete' => '?',
            'App\\Controller\\AnimauxController:edit' => '?',
            'App\\Controller\\AnimauxController:index' => '?',
            'App\\Controller\\AnimauxController:new' => '?',
            'App\\Controller\\AnimauxController:show' => '?',
            'App\\Controller\\ExamensController:delete' => '?',
            'App\\Controller\\ExamensController:edit' => '?',
            'App\\Controller\\ExamensController:index' => '?',
            'App\\Controller\\ExamensController:new' => '?',
            'App\\Controller\\ExamensController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.FvJHjid'])) {
            return $container->privates['.service_locator.FvJHjid'];
        }

        return $container->privates['.service_locator.FvJHjid'] = $instance;
    }
}
