<?php

namespace Container5jCnL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H2SgVt9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H2SgVt9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H2SgVt9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animauxRepository' => ['privates', 'App\\Repository\\AnimauxRepository', 'getAnimauxRepositoryService', true],
        ], [
            'animauxRepository' => 'App\\Repository\\AnimauxRepository',
        ]);
    }
}
