<?php

namespace Container5jCnL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HZqfXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h__ZqfX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h__ZqfX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'examen' => ['privates', '.errored..service_locator.h__ZqfX.App\\Entity\\Examen', NULL, 'Cannot autowire service ".service_locator.h__ZqfX": it needs an instance of "App\\Entity\\Examen" but this type has been excluded in "config/services.yaml".'],
        ], [
            'examen' => 'App\\Entity\\Examen',
        ]);
    }
}
