<?php

namespace Container5jCnL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AVVMrX4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aVVMrX4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animaux' => ['privates', '.errored..service_locator.aVVMrX4.App\\Entity\\Animaux', NULL, 'Cannot autowire service ".service_locator.aVVMrX4": it needs an instance of "App\\Entity\\Animaux" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'animaux' => 'App\\Entity\\Animaux',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.aVVMrX4'])) {
            return $container->privates['.service_locator.aVVMrX4'];
        }

        return $container->privates['.service_locator.aVVMrX4'] = $instance;
    }
}
