<?php

namespace Container5jCnL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_93oAlYQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.93oAlYQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.93oAlYQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animaux' => ['privates', '.errored..service_locator.93oAlYQ.App\\Entity\\Animaux', NULL, 'Cannot autowire service ".service_locator.93oAlYQ": it needs an instance of "App\\Entity\\Animaux" but this type has been excluded in "config/services.yaml".'],
        ], [
            'animaux' => 'App\\Entity\\Animaux',
        ]);
    }
}
