<?php

namespace Container5jCnL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimauxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.93oAlYQ.App\Entity\Animaux' shared service.
     *
     * @return \App\Entity\Animaux
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.93oAlYQ": it needs an instance of "App\\Entity\\Animaux" but this type has been excluded in "config/services.yaml".');
    }
}
