<?php

namespace Container5jCnL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h__ZqfX.App\Entity\Examen' shared service.
     *
     * @return \App\Entity\Examen
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h__ZqfX": it needs an instance of "App\\Entity\\Examen" but this type has been excluded in "config/services.yaml".');
    }
}
