<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZUNxSJ7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZUNxSJ7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZUNxSJ7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZUNxSJ7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZUNxSJ7\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZUNxSJ7',
    'container.build_id' => '8eb52d5a',
    'container.build_time' => 1775641693,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZUNxSJ7');
