<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIQvf25p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIQvf25p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIQvf25p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIQvf25p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIQvf25p\App_KernelDevDebugContainer([
    'container.build_hash' => 'IQvf25p',
    'container.build_id' => '2f6b5a6e',
    'container.build_time' => 1775660588,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIQvf25p');
