<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTx5hmHF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx5hmHF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTx5hmHF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTx5hmHF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTx5hmHF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tx5hmHF',
    'container.build_id' => '136c0a3e',
    'container.build_time' => 1776795144,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx5hmHF');
